# Generated by Django 6.1 on 2026-08-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id_decision', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('id_agente', models.CharField(choices=[('ORQUESTADOR', 'Orquestador'), ('AGENTE_DESPENSA', 'Agente Despensa'), ('AGENTE_CONSUMO', 'Agente Consumo'), ('AGENTE_PRESUPUESTO', 'Agente Presupuesto'), ('AGENTE_MANTENIMIENTO', 'Agente Mantenimiento')], max_length=32)),
                ('accion_tomada', models.CharField(max_length=255)),
                ('justificacion_tecnica', models.TextField()),
                ('detalles_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'decision_log',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
    ]
