# Generated by Django 6.1 on 2026-08-14 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoLog',
            fields=[
                ('id_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('tipo_servicio', models.CharField(choices=[('AGUA', 'Agua'), ('LUZ', 'Luz'), ('GAS', 'Gas')], max_length=16)),
                ('valor_medicion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('etiqueta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'consumo_log',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('prioridad', models.IntegerField()),
                ('fecha_ultimo_service', models.DateField(blank=True, null=True)),
                ('vida_util_estimada', models.IntegerField()),
                ('estado_actual', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('REQUIERE_SERVICE', 'Requiere Service'), ('EN_MANTENIMIENTO', 'En Mantenimiento'), ('WAITING_HUMAN_APPROVAL', 'Waiting Human Approval'), ('FUERA_DE_SERVICIO', 'Fuera De Servicio')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dispositivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemDespensa',
            fields=[
                ('id_item', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consumo_promedio_diario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'item_despensa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100, unique=True)),
                ('limite_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_gastado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_esencial', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'presupuesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id_residente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=32, unique=True)),
                ('nivel_permiso', models.CharField(choices=[('ADMIN', 'Admin'), ('RESIDENTE', 'Residente'), ('INVITADO', 'Invitado')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'residente',
                'managed': False,
            },
        ),
    ]
