# Generated by Django 6.1 on 2026-08-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estadosimulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresosHogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingresos_hogar',
            },
        ),
    ]
