# Generated by Django 6.1 on 2026-08-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingresoshogar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoshogar',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
