# Generated by Django 6.1 on 2026-08-24 13:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingresoshogar_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoshogar',
            name='ahorros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ingresoshogar',
            name='porcentaje_ahorrable',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5),
        ),
    ]
